// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: order_deliverer.proto

package order_proto_gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterDelivererRequest struct {
	state               protoimpl.MessageState        `protogen:"open.v1"`
	UserId              int64                         `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IdCardNumber        string                        `protobuf:"bytes,2,opt,name=id_card_number,json=idCardNumber,proto3" json:"id_card_number,omitempty"`
	IdCardFrontImage    string                        `protobuf:"bytes,3,opt,name=id_card_front_image,json=idCardFrontImage,proto3" json:"id_card_front_image,omitempty"`
	IdCardBackImage     string                        `protobuf:"bytes,4,opt,name=id_card_back_image,json=idCardBackImage,proto3" json:"id_card_back_image,omitempty"`
	VehicleType         string                        `protobuf:"bytes,5,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	VehicleLicensePlate string                        `protobuf:"bytes,6,opt,name=vehicle_license_plate,json=vehicleLicensePlate,proto3" json:"vehicle_license_plate,omitempty"`
	ServiceArea         *RegisterDelivererServiceArea `protobuf:"bytes,7,opt,name=service_area,json=serviceArea,proto3" json:"service_area,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RegisterDelivererRequest) Reset() {
	*x = RegisterDelivererRequest{}
	mi := &file_order_deliverer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDelivererRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDelivererRequest) ProtoMessage() {}

func (x *RegisterDelivererRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_deliverer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDelivererRequest.ProtoReflect.Descriptor instead.
func (*RegisterDelivererRequest) Descriptor() ([]byte, []int) {
	return file_order_deliverer_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterDelivererRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RegisterDelivererRequest) GetIdCardNumber() string {
	if x != nil {
		return x.IdCardNumber
	}
	return ""
}

func (x *RegisterDelivererRequest) GetIdCardFrontImage() string {
	if x != nil {
		return x.IdCardFrontImage
	}
	return ""
}

func (x *RegisterDelivererRequest) GetIdCardBackImage() string {
	if x != nil {
		return x.IdCardBackImage
	}
	return ""
}

func (x *RegisterDelivererRequest) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *RegisterDelivererRequest) GetVehicleLicensePlate() string {
	if x != nil {
		return x.VehicleLicensePlate
	}
	return ""
}

func (x *RegisterDelivererRequest) GetServiceArea() *RegisterDelivererServiceArea {
	if x != nil {
		return x.ServiceArea
	}
	return nil
}

type RegisterDelivererServiceArea struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Country       string                 `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	District      string                 `protobuf:"bytes,3,opt,name=district,proto3" json:"district,omitempty"`
	Ward          string                 `protobuf:"bytes,4,opt,name=ward,proto3" json:"ward,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDelivererServiceArea) Reset() {
	*x = RegisterDelivererServiceArea{}
	mi := &file_order_deliverer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDelivererServiceArea) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDelivererServiceArea) ProtoMessage() {}

func (x *RegisterDelivererServiceArea) ProtoReflect() protoreflect.Message {
	mi := &file_order_deliverer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDelivererServiceArea.ProtoReflect.Descriptor instead.
func (*RegisterDelivererServiceArea) Descriptor() ([]byte, []int) {
	return file_order_deliverer_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterDelivererServiceArea) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *RegisterDelivererServiceArea) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *RegisterDelivererServiceArea) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *RegisterDelivererServiceArea) GetWard() string {
	if x != nil {
		return x.Ward
	}
	return ""
}

type RegisterDelivererResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDelivererResponse) Reset() {
	*x = RegisterDelivererResponse{}
	mi := &file_order_deliverer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDelivererResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDelivererResponse) ProtoMessage() {}

func (x *RegisterDelivererResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_deliverer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDelivererResponse.ProtoReflect.Descriptor instead.
func (*RegisterDelivererResponse) Descriptor() ([]byte, []int) {
	return file_order_deliverer_proto_rawDescGZIP(), []int{2}
}

var File_order_deliverer_proto protoreflect.FileDescriptor

var file_order_deliverer_proto_rawDesc = string([]byte{
	0x0a, 0x15, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xce, 0x02, 0x0a, 0x18, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x24, 0x0a,
	0x0e, 0x69, 0x64, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x69, 0x64, 0x43, 0x61, 0x72, 0x64, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x2d, 0x0a, 0x13, 0x69, 0x64, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x66,
	0x72, 0x6f, 0x6e, 0x74, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x10, 0x69, 0x64, 0x43, 0x61, 0x72, 0x64, 0x46, 0x72, 0x6f, 0x6e, 0x74, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x12, 0x2b, 0x0a, 0x12, 0x69, 0x64, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x62, 0x61,
	0x63, 0x6b, 0x5f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f,
	0x69, 0x64, 0x43, 0x61, 0x72, 0x64, 0x42, 0x61, 0x63, 0x6b, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12,
	0x21, 0x0a, 0x0c, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x32, 0x0a, 0x15, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x5f, 0x6c, 0x69,
	0x63, 0x65, 0x6e, 0x73, 0x65, 0x5f, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x13, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x4c, 0x69, 0x63, 0x65, 0x6e, 0x73,
	0x65, 0x50, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x40, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x5f, 0x61, 0x72, 0x65, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x65, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x72, 0x65, 0x61, 0x52, 0x0b, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x41, 0x72, 0x65, 0x61, 0x22, 0x7c, 0x0a, 0x1c, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x65, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x41, 0x72, 0x65, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69,
	0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69,
	0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x61, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x77, 0x61, 0x72, 0x64, 0x22, 0x1b, 0x0a, 0x19, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_order_deliverer_proto_rawDescOnce sync.Once
	file_order_deliverer_proto_rawDescData []byte
)

func file_order_deliverer_proto_rawDescGZIP() []byte {
	file_order_deliverer_proto_rawDescOnce.Do(func() {
		file_order_deliverer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_deliverer_proto_rawDesc), len(file_order_deliverer_proto_rawDesc)))
	})
	return file_order_deliverer_proto_rawDescData
}

var file_order_deliverer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_order_deliverer_proto_goTypes = []any{
	(*RegisterDelivererRequest)(nil),     // 0: RegisterDelivererRequest
	(*RegisterDelivererServiceArea)(nil), // 1: RegisterDelivererServiceArea
	(*RegisterDelivererResponse)(nil),    // 2: RegisterDelivererResponse
}
var file_order_deliverer_proto_depIdxs = []int32{
	1, // 0: RegisterDelivererRequest.service_area:type_name -> RegisterDelivererServiceArea
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_order_deliverer_proto_init() }
func file_order_deliverer_proto_init() {
	if File_order_deliverer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_deliverer_proto_rawDesc), len(file_order_deliverer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_order_deliverer_proto_goTypes,
		DependencyIndexes: file_order_deliverer_proto_depIdxs,
		MessageInfos:      file_order_deliverer_proto_msgTypes,
	}.Build()
	File_order_deliverer_proto = out.File
	file_order_deliverer_proto_goTypes = nil
	file_order_deliverer_proto_depIdxs = nil
}
