// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: get_notification_preferences.proto

package notification_proto_gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetEmailNotificationPreferencesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderStatus   bool                   `protobuf:"varint,1,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	PaymentStatus bool                   `protobuf:"varint,2,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"`
	ProductStatus bool                   `protobuf:"varint,3,opt,name=product_status,json=productStatus,proto3" json:"product_status,omitempty"`
	Promotion     bool                   `protobuf:"varint,4,opt,name=promotion,proto3" json:"promotion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmailNotificationPreferencesResponse) Reset() {
	*x = GetEmailNotificationPreferencesResponse{}
	mi := &file_get_notification_preferences_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmailNotificationPreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmailNotificationPreferencesResponse) ProtoMessage() {}

func (x *GetEmailNotificationPreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_get_notification_preferences_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmailNotificationPreferencesResponse.ProtoReflect.Descriptor instead.
func (*GetEmailNotificationPreferencesResponse) Descriptor() ([]byte, []int) {
	return file_get_notification_preferences_proto_rawDescGZIP(), []int{0}
}

func (x *GetEmailNotificationPreferencesResponse) GetOrderStatus() bool {
	if x != nil {
		return x.OrderStatus
	}
	return false
}

func (x *GetEmailNotificationPreferencesResponse) GetPaymentStatus() bool {
	if x != nil {
		return x.PaymentStatus
	}
	return false
}

func (x *GetEmailNotificationPreferencesResponse) GetProductStatus() bool {
	if x != nil {
		return x.ProductStatus
	}
	return false
}

func (x *GetEmailNotificationPreferencesResponse) GetPromotion() bool {
	if x != nil {
		return x.Promotion
	}
	return false
}

type GetInAppNotificationPreferencesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderStatus   bool                   `protobuf:"varint,1,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	PaymentStatus bool                   `protobuf:"varint,2,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"`
	ProductStatus bool                   `protobuf:"varint,3,opt,name=product_status,json=productStatus,proto3" json:"product_status,omitempty"`
	Promotion     bool                   `protobuf:"varint,4,opt,name=promotion,proto3" json:"promotion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInAppNotificationPreferencesResponse) Reset() {
	*x = GetInAppNotificationPreferencesResponse{}
	mi := &file_get_notification_preferences_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInAppNotificationPreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInAppNotificationPreferencesResponse) ProtoMessage() {}

func (x *GetInAppNotificationPreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_get_notification_preferences_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInAppNotificationPreferencesResponse.ProtoReflect.Descriptor instead.
func (*GetInAppNotificationPreferencesResponse) Descriptor() ([]byte, []int) {
	return file_get_notification_preferences_proto_rawDescGZIP(), []int{1}
}

func (x *GetInAppNotificationPreferencesResponse) GetOrderStatus() bool {
	if x != nil {
		return x.OrderStatus
	}
	return false
}

func (x *GetInAppNotificationPreferencesResponse) GetPaymentStatus() bool {
	if x != nil {
		return x.PaymentStatus
	}
	return false
}

func (x *GetInAppNotificationPreferencesResponse) GetProductStatus() bool {
	if x != nil {
		return x.ProductStatus
	}
	return false
}

func (x *GetInAppNotificationPreferencesResponse) GetPromotion() bool {
	if x != nil {
		return x.Promotion
	}
	return false
}

var File_get_notification_preferences_proto protoreflect.FileDescriptor

var file_get_notification_preferences_proto_rawDesc = string([]byte{
	0x0a, 0x22, 0x67, 0x65, 0x74, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb8, 0x01, 0x0a, 0x27, 0x47, 0x65, 0x74, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x65,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x70, 0x61, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0d, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0xb8, 0x01, 0x0a, 0x27, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x41, 0x70, 0x70, 0x4e, 0x6f, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x25,
	0x0a, 0x0e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x09,
	0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x09, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x1a, 0x5a, 0x18, 0x2e, 0x2f,
	0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_get_notification_preferences_proto_rawDescOnce sync.Once
	file_get_notification_preferences_proto_rawDescData []byte
)

func file_get_notification_preferences_proto_rawDescGZIP() []byte {
	file_get_notification_preferences_proto_rawDescOnce.Do(func() {
		file_get_notification_preferences_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_get_notification_preferences_proto_rawDesc), len(file_get_notification_preferences_proto_rawDesc)))
	})
	return file_get_notification_preferences_proto_rawDescData
}

var file_get_notification_preferences_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_get_notification_preferences_proto_goTypes = []any{
	(*GetEmailNotificationPreferencesResponse)(nil), // 0: GetEmailNotificationPreferencesResponse
	(*GetInAppNotificationPreferencesResponse)(nil), // 1: GetInAppNotificationPreferencesResponse
}
var file_get_notification_preferences_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_get_notification_preferences_proto_init() }
func file_get_notification_preferences_proto_init() {
	if File_get_notification_preferences_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_get_notification_preferences_proto_rawDesc), len(file_get_notification_preferences_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_get_notification_preferences_proto_goTypes,
		DependencyIndexes: file_get_notification_preferences_proto_depIdxs,
		MessageInfos:      file_get_notification_preferences_proto_msgTypes,
	}.Build()
	File_get_notification_preferences_proto = out.File
	file_get_notification_preferences_proto_goTypes = nil
	file_get_notification_preferences_proto_depIdxs = nil
}
