// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: update_notification_preferences.proto

package notification_proto_gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateEmailNotificationPreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderStatus   bool                   `protobuf:"varint,1,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	PaymentStatus bool                   `protobuf:"varint,2,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"`
	ProductStatus bool                   `protobuf:"varint,3,opt,name=product_status,json=productStatus,proto3" json:"product_status,omitempty"`
	Promotion     bool                   `protobuf:"varint,4,opt,name=promotion,proto3" json:"promotion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmailNotificationPreferencesRequest) Reset() {
	*x = UpdateEmailNotificationPreferencesRequest{}
	mi := &file_update_notification_preferences_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmailNotificationPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmailNotificationPreferencesRequest) ProtoMessage() {}

func (x *UpdateEmailNotificationPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_update_notification_preferences_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmailNotificationPreferencesRequest.ProtoReflect.Descriptor instead.
func (*UpdateEmailNotificationPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_update_notification_preferences_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateEmailNotificationPreferencesRequest) GetOrderStatus() bool {
	if x != nil {
		return x.OrderStatus
	}
	return false
}

func (x *UpdateEmailNotificationPreferencesRequest) GetPaymentStatus() bool {
	if x != nil {
		return x.PaymentStatus
	}
	return false
}

func (x *UpdateEmailNotificationPreferencesRequest) GetProductStatus() bool {
	if x != nil {
		return x.ProductStatus
	}
	return false
}

func (x *UpdateEmailNotificationPreferencesRequest) GetPromotion() bool {
	if x != nil {
		return x.Promotion
	}
	return false
}

type UpdateEmailNotificationPreferencesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderStatus   bool                   `protobuf:"varint,1,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	PaymentStatus bool                   `protobuf:"varint,2,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"`
	ProductStatus bool                   `protobuf:"varint,3,opt,name=product_status,json=productStatus,proto3" json:"product_status,omitempty"`
	Promotion     bool                   `protobuf:"varint,4,opt,name=promotion,proto3" json:"promotion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmailNotificationPreferencesResponse) Reset() {
	*x = UpdateEmailNotificationPreferencesResponse{}
	mi := &file_update_notification_preferences_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmailNotificationPreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmailNotificationPreferencesResponse) ProtoMessage() {}

func (x *UpdateEmailNotificationPreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_update_notification_preferences_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmailNotificationPreferencesResponse.ProtoReflect.Descriptor instead.
func (*UpdateEmailNotificationPreferencesResponse) Descriptor() ([]byte, []int) {
	return file_update_notification_preferences_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateEmailNotificationPreferencesResponse) GetOrderStatus() bool {
	if x != nil {
		return x.OrderStatus
	}
	return false
}

func (x *UpdateEmailNotificationPreferencesResponse) GetPaymentStatus() bool {
	if x != nil {
		return x.PaymentStatus
	}
	return false
}

func (x *UpdateEmailNotificationPreferencesResponse) GetProductStatus() bool {
	if x != nil {
		return x.ProductStatus
	}
	return false
}

func (x *UpdateEmailNotificationPreferencesResponse) GetPromotion() bool {
	if x != nil {
		return x.Promotion
	}
	return false
}

type UpdateInAppNotificationPreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderStatus   bool                   `protobuf:"varint,1,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	PaymentStatus bool                   `protobuf:"varint,2,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"`
	ProductStatus bool                   `protobuf:"varint,3,opt,name=product_status,json=productStatus,proto3" json:"product_status,omitempty"`
	Promotion     bool                   `protobuf:"varint,4,opt,name=promotion,proto3" json:"promotion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInAppNotificationPreferencesRequest) Reset() {
	*x = UpdateInAppNotificationPreferencesRequest{}
	mi := &file_update_notification_preferences_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInAppNotificationPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInAppNotificationPreferencesRequest) ProtoMessage() {}

func (x *UpdateInAppNotificationPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_update_notification_preferences_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInAppNotificationPreferencesRequest.ProtoReflect.Descriptor instead.
func (*UpdateInAppNotificationPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_update_notification_preferences_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateInAppNotificationPreferencesRequest) GetOrderStatus() bool {
	if x != nil {
		return x.OrderStatus
	}
	return false
}

func (x *UpdateInAppNotificationPreferencesRequest) GetPaymentStatus() bool {
	if x != nil {
		return x.PaymentStatus
	}
	return false
}

func (x *UpdateInAppNotificationPreferencesRequest) GetProductStatus() bool {
	if x != nil {
		return x.ProductStatus
	}
	return false
}

func (x *UpdateInAppNotificationPreferencesRequest) GetPromotion() bool {
	if x != nil {
		return x.Promotion
	}
	return false
}

type UpdateInAppNotificationPreferencesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderStatus   bool                   `protobuf:"varint,1,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	PaymentStatus bool                   `protobuf:"varint,2,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"`
	ProductStatus bool                   `protobuf:"varint,3,opt,name=product_status,json=productStatus,proto3" json:"product_status,omitempty"`
	Promotion     bool                   `protobuf:"varint,4,opt,name=promotion,proto3" json:"promotion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInAppNotificationPreferencesResponse) Reset() {
	*x = UpdateInAppNotificationPreferencesResponse{}
	mi := &file_update_notification_preferences_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInAppNotificationPreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInAppNotificationPreferencesResponse) ProtoMessage() {}

func (x *UpdateInAppNotificationPreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_update_notification_preferences_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInAppNotificationPreferencesResponse.ProtoReflect.Descriptor instead.
func (*UpdateInAppNotificationPreferencesResponse) Descriptor() ([]byte, []int) {
	return file_update_notification_preferences_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateInAppNotificationPreferencesResponse) GetOrderStatus() bool {
	if x != nil {
		return x.OrderStatus
	}
	return false
}

func (x *UpdateInAppNotificationPreferencesResponse) GetPaymentStatus() bool {
	if x != nil {
		return x.PaymentStatus
	}
	return false
}

func (x *UpdateInAppNotificationPreferencesResponse) GetProductStatus() bool {
	if x != nil {
		return x.ProductStatus
	}
	return false
}

func (x *UpdateInAppNotificationPreferencesResponse) GetPromotion() bool {
	if x != nil {
		return x.Promotion
	}
	return false
}

var File_update_notification_preferences_proto protoreflect.FileDescriptor

var file_update_notification_preferences_proto_rawDesc = string([]byte{
	0x0a, 0x25, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xba, 0x01, 0x0a, 0x29, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x6f, 0x72, 0x64,
	0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x61, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0d, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x25, 0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6d, 0x6f,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0xbb, 0x01, 0x0a, 0x2a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x50, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d,
	0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x25, 0x0a,
	0x0e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0xba, 0x01, 0x0a, 0x29, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x41,
	0x70, 0x70, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x70, 0x61, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0d, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0xbb, 0x01, 0x0a, 0x2a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x41, 0x70, 0x70, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x72, 0x65, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21,
	0x0a, 0x0c, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x70, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0d, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x1c, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x1a, 0x5a,
	0x18, 0x2e, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
})

var (
	file_update_notification_preferences_proto_rawDescOnce sync.Once
	file_update_notification_preferences_proto_rawDescData []byte
)

func file_update_notification_preferences_proto_rawDescGZIP() []byte {
	file_update_notification_preferences_proto_rawDescOnce.Do(func() {
		file_update_notification_preferences_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_update_notification_preferences_proto_rawDesc), len(file_update_notification_preferences_proto_rawDesc)))
	})
	return file_update_notification_preferences_proto_rawDescData
}

var file_update_notification_preferences_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_update_notification_preferences_proto_goTypes = []any{
	(*UpdateEmailNotificationPreferencesRequest)(nil),  // 0: UpdateEmailNotificationPreferencesRequest
	(*UpdateEmailNotificationPreferencesResponse)(nil), // 1: UpdateEmailNotificationPreferencesResponse
	(*UpdateInAppNotificationPreferencesRequest)(nil),  // 2: UpdateInAppNotificationPreferencesRequest
	(*UpdateInAppNotificationPreferencesResponse)(nil), // 3: UpdateInAppNotificationPreferencesResponse
}
var file_update_notification_preferences_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_update_notification_preferences_proto_init() }
func file_update_notification_preferences_proto_init() {
	if File_update_notification_preferences_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_update_notification_preferences_proto_rawDesc), len(file_update_notification_preferences_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_update_notification_preferences_proto_goTypes,
		DependencyIndexes: file_update_notification_preferences_proto_depIdxs,
		MessageInfos:      file_update_notification_preferences_proto_msgTypes,
	}.Build()
	File_update_notification_preferences_proto = out.File
	file_update_notification_preferences_proto_goTypes = nil
	file_update_notification_preferences_proto_depIdxs = nil
}
