@startuml Quản lý Đơn hàng giao

actor "Người dùng" as nd

boundary "Web UI" as UI
control "API Gateway service" as Gateway
control "Partner Service" as PartnerService
database "Partner DB" as partnerdb

nd -> UI: 1. Truy cập trang chủ
UI -> Gateway: 2. Lấy danh sách danh mục
Gateway -> PartnerService: 3. Chuyển yêu cầu lấy\n danh sách danh mục
PartnerService -> partnerdb: 4. Lấy dữ liệu danh mục
partnerdb --> PartnerService: 5. Trả về danh sách danh mục

PartnerService --> Gateway: 6. Trả về danh sách danh mục

Gateway --> UI: 7. Trả về dữ liệu
UI -> UI: 8. Hiển thị danh sách danh mục

@enduml