@startuml
' Use horizontal layout with actors on both sides
left to right direction

' Improve visual appearance
skinparam usecase {
  BackgroundColor white
  BorderColor black
  ArrowColor black
}
skinparam linetype polyline

' Actors
actor "Người giao hàng" as ngh

usecase "Quản lý đơn hàng giao" as UC1

ngh --> UC1

@enduml