// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: main.proto

package partner_proto_gen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PartnerService_GetCategories_FullMethodName         = "/PartnerService/GetCategories"
	PartnerService_GetProducts_FullMethodName           = "/PartnerService/GetProducts"
	PartnerService_GetProductByID_FullMethodName        = "/PartnerService/GetProductByID"
	PartnerService_GetProductReviewsByID_FullMethodName = "/PartnerService/GetProductReviewsByID"
	PartnerService_CheckAvailableProduct_FullMethodName = "/PartnerService/CheckAvailableProduct"
	PartnerService_GetProductInfoCart_FullMethodName    = "/PartnerService/GetProductInfoCart"
	PartnerService_GetProdInfoForPayment_FullMethodName = "/PartnerService/GetProdInfoForPayment"
)

// PartnerServiceClient is the client API for PartnerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PartnerServiceClient interface {
	GetCategories(ctx context.Context, in *GetCategoriesRequest, opts ...grpc.CallOption) (*GetCategoriesResponse, error)
	GetProducts(ctx context.Context, in *GetProductsRequest, opts ...grpc.CallOption) (*GetProductsResponse, error)
	GetProductByID(ctx context.Context, in *GetProductDetailRequest, opts ...grpc.CallOption) (*GetProductDetailResponse, error)
	GetProductReviewsByID(ctx context.Context, in *GetProductReviewsRequest, opts ...grpc.CallOption) (*GetProductReviewsResponse, error)
	CheckAvailableProduct(ctx context.Context, in *CheckAvailableProductRequest, opts ...grpc.CallOption) (*CheckAvailableProductResponse, error)
	GetProductInfoCart(ctx context.Context, in *GetProductInfoCartRequest, opts ...grpc.CallOption) (*GetProductInfoCartResponse, error)
	GetProdInfoForPayment(ctx context.Context, in *GetProdInfoForPaymentRequest, opts ...grpc.CallOption) (*GetProdInfoForPaymentResponse, error)
}

type partnerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPartnerServiceClient(cc grpc.ClientConnInterface) PartnerServiceClient {
	return &partnerServiceClient{cc}
}

func (c *partnerServiceClient) GetCategories(ctx context.Context, in *GetCategoriesRequest, opts ...grpc.CallOption) (*GetCategoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCategoriesResponse)
	err := c.cc.Invoke(ctx, PartnerService_GetCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partnerServiceClient) GetProducts(ctx context.Context, in *GetProductsRequest, opts ...grpc.CallOption) (*GetProductsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductsResponse)
	err := c.cc.Invoke(ctx, PartnerService_GetProducts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partnerServiceClient) GetProductByID(ctx context.Context, in *GetProductDetailRequest, opts ...grpc.CallOption) (*GetProductDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductDetailResponse)
	err := c.cc.Invoke(ctx, PartnerService_GetProductByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partnerServiceClient) GetProductReviewsByID(ctx context.Context, in *GetProductReviewsRequest, opts ...grpc.CallOption) (*GetProductReviewsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductReviewsResponse)
	err := c.cc.Invoke(ctx, PartnerService_GetProductReviewsByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partnerServiceClient) CheckAvailableProduct(ctx context.Context, in *CheckAvailableProductRequest, opts ...grpc.CallOption) (*CheckAvailableProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckAvailableProductResponse)
	err := c.cc.Invoke(ctx, PartnerService_CheckAvailableProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partnerServiceClient) GetProductInfoCart(ctx context.Context, in *GetProductInfoCartRequest, opts ...grpc.CallOption) (*GetProductInfoCartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductInfoCartResponse)
	err := c.cc.Invoke(ctx, PartnerService_GetProductInfoCart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *partnerServiceClient) GetProdInfoForPayment(ctx context.Context, in *GetProdInfoForPaymentRequest, opts ...grpc.CallOption) (*GetProdInfoForPaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProdInfoForPaymentResponse)
	err := c.cc.Invoke(ctx, PartnerService_GetProdInfoForPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PartnerServiceServer is the server API for PartnerService service.
// All implementations must embed UnimplementedPartnerServiceServer
// for forward compatibility.
type PartnerServiceServer interface {
	GetCategories(context.Context, *GetCategoriesRequest) (*GetCategoriesResponse, error)
	GetProducts(context.Context, *GetProductsRequest) (*GetProductsResponse, error)
	GetProductByID(context.Context, *GetProductDetailRequest) (*GetProductDetailResponse, error)
	GetProductReviewsByID(context.Context, *GetProductReviewsRequest) (*GetProductReviewsResponse, error)
	CheckAvailableProduct(context.Context, *CheckAvailableProductRequest) (*CheckAvailableProductResponse, error)
	GetProductInfoCart(context.Context, *GetProductInfoCartRequest) (*GetProductInfoCartResponse, error)
	GetProdInfoForPayment(context.Context, *GetProdInfoForPaymentRequest) (*GetProdInfoForPaymentResponse, error)
	mustEmbedUnimplementedPartnerServiceServer()
}

// UnimplementedPartnerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPartnerServiceServer struct{}

func (UnimplementedPartnerServiceServer) GetCategories(context.Context, *GetCategoriesRequest) (*GetCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCategories not implemented")
}
func (UnimplementedPartnerServiceServer) GetProducts(context.Context, *GetProductsRequest) (*GetProductsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProducts not implemented")
}
func (UnimplementedPartnerServiceServer) GetProductByID(context.Context, *GetProductDetailRequest) (*GetProductDetailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductByID not implemented")
}
func (UnimplementedPartnerServiceServer) GetProductReviewsByID(context.Context, *GetProductReviewsRequest) (*GetProductReviewsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductReviewsByID not implemented")
}
func (UnimplementedPartnerServiceServer) CheckAvailableProduct(context.Context, *CheckAvailableProductRequest) (*CheckAvailableProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAvailableProduct not implemented")
}
func (UnimplementedPartnerServiceServer) GetProductInfoCart(context.Context, *GetProductInfoCartRequest) (*GetProductInfoCartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProductInfoCart not implemented")
}
func (UnimplementedPartnerServiceServer) GetProdInfoForPayment(context.Context, *GetProdInfoForPaymentRequest) (*GetProdInfoForPaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProdInfoForPayment not implemented")
}
func (UnimplementedPartnerServiceServer) mustEmbedUnimplementedPartnerServiceServer() {}
func (UnimplementedPartnerServiceServer) testEmbeddedByValue()                        {}

// UnsafePartnerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PartnerServiceServer will
// result in compilation errors.
type UnsafePartnerServiceServer interface {
	mustEmbedUnimplementedPartnerServiceServer()
}

func RegisterPartnerServiceServer(s grpc.ServiceRegistrar, srv PartnerServiceServer) {
	// If the following call pancis, it indicates UnimplementedPartnerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PartnerService_ServiceDesc, srv)
}

func _PartnerService_GetCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartnerServiceServer).GetCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartnerService_GetCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartnerServiceServer).GetCategories(ctx, req.(*GetCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartnerService_GetProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartnerServiceServer).GetProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartnerService_GetProducts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartnerServiceServer).GetProducts(ctx, req.(*GetProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartnerService_GetProductByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartnerServiceServer).GetProductByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartnerService_GetProductByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartnerServiceServer).GetProductByID(ctx, req.(*GetProductDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartnerService_GetProductReviewsByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductReviewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartnerServiceServer).GetProductReviewsByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartnerService_GetProductReviewsByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartnerServiceServer).GetProductReviewsByID(ctx, req.(*GetProductReviewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartnerService_CheckAvailableProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAvailableProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartnerServiceServer).CheckAvailableProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartnerService_CheckAvailableProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartnerServiceServer).CheckAvailableProduct(ctx, req.(*CheckAvailableProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartnerService_GetProductInfoCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductInfoCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartnerServiceServer).GetProductInfoCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartnerService_GetProductInfoCart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartnerServiceServer).GetProductInfoCart(ctx, req.(*GetProductInfoCartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PartnerService_GetProdInfoForPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProdInfoForPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PartnerServiceServer).GetProdInfoForPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PartnerService_GetProdInfoForPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PartnerServiceServer).GetProdInfoForPayment(ctx, req.(*GetProdInfoForPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PartnerService_ServiceDesc is the grpc.ServiceDesc for PartnerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PartnerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "PartnerService",
	HandlerType: (*PartnerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCategories",
			Handler:    _PartnerService_GetCategories_Handler,
		},
		{
			MethodName: "GetProducts",
			Handler:    _PartnerService_GetProducts_Handler,
		},
		{
			MethodName: "GetProductByID",
			Handler:    _PartnerService_GetProductByID_Handler,
		},
		{
			MethodName: "GetProductReviewsByID",
			Handler:    _PartnerService_GetProductReviewsByID_Handler,
		},
		{
			MethodName: "CheckAvailableProduct",
			Handler:    _PartnerService_CheckAvailableProduct_Handler,
		},
		{
			MethodName: "GetProductInfoCart",
			Handler:    _PartnerService_GetProductInfoCart_Handler,
		},
		{
			MethodName: "GetProdInfoForPayment",
			Handler:    _PartnerService_GetProdInfoForPayment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "main.proto",
}
