// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: partner_payment.proto

package partner_proto_gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProdInfoForPaymentRequest struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Items         []*ProdInfoForPaymentRequest `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProdInfoForPaymentRequest) Reset() {
	*x = GetProdInfoForPaymentRequest{}
	mi := &file_partner_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProdInfoForPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProdInfoForPaymentRequest) ProtoMessage() {}

func (x *GetProdInfoForPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_partner_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProdInfoForPaymentRequest.ProtoReflect.Descriptor instead.
func (*GetProdInfoForPaymentRequest) Descriptor() ([]byte, []int) {
	return file_partner_payment_proto_rawDescGZIP(), []int{0}
}

func (x *GetProdInfoForPaymentRequest) GetItems() []*ProdInfoForPaymentRequest {
	if x != nil {
		return x.Items
	}
	return nil
}

type ProdInfoForPaymentRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProductVariantId string                 `protobuf:"bytes,1,opt,name=product_variant_id,json=productVariantId,proto3" json:"product_variant_id,omitempty"`
	Quantity         int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProdInfoForPaymentRequest) Reset() {
	*x = ProdInfoForPaymentRequest{}
	mi := &file_partner_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProdInfoForPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProdInfoForPaymentRequest) ProtoMessage() {}

func (x *ProdInfoForPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_partner_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProdInfoForPaymentRequest.ProtoReflect.Descriptor instead.
func (*ProdInfoForPaymentRequest) Descriptor() ([]byte, []int) {
	return file_partner_payment_proto_rawDescGZIP(), []int{1}
}

func (x *ProdInfoForPaymentRequest) GetProductVariantId() string {
	if x != nil {
		return x.ProductVariantId
	}
	return ""
}

func (x *ProdInfoForPaymentRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type GetProdInfoForPaymentResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Items         []*ProdInfoForPaymentResponse `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProdInfoForPaymentResponse) Reset() {
	*x = GetProdInfoForPaymentResponse{}
	mi := &file_partner_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProdInfoForPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProdInfoForPaymentResponse) ProtoMessage() {}

func (x *GetProdInfoForPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_partner_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProdInfoForPaymentResponse.ProtoReflect.Descriptor instead.
func (*GetProdInfoForPaymentResponse) Descriptor() ([]byte, []int) {
	return file_partner_payment_proto_rawDescGZIP(), []int{2}
}

func (x *GetProdInfoForPaymentResponse) GetItems() []*ProdInfoForPaymentResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

type ProdInfoForPaymentResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProductVariantId  string                 `protobuf:"bytes,1,opt,name=product_variant_id,json=productVariantId,proto3" json:"product_variant_id,omitempty"`
	OriginalUnitPrice float64                `protobuf:"fixed64,2,opt,name=original_unit_price,json=originalUnitPrice,proto3" json:"original_unit_price,omitempty"`
	DiscountUnitPrice float64                `protobuf:"fixed64,3,opt,name=discount_unit_price,json=discountUnitPrice,proto3" json:"discount_unit_price,omitempty"`
	TaxClass          string                 `protobuf:"bytes,4,opt,name=tax_class,json=taxClass,proto3" json:"tax_class,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProdInfoForPaymentResponse) Reset() {
	*x = ProdInfoForPaymentResponse{}
	mi := &file_partner_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProdInfoForPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProdInfoForPaymentResponse) ProtoMessage() {}

func (x *ProdInfoForPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_partner_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProdInfoForPaymentResponse.ProtoReflect.Descriptor instead.
func (*ProdInfoForPaymentResponse) Descriptor() ([]byte, []int) {
	return file_partner_payment_proto_rawDescGZIP(), []int{3}
}

func (x *ProdInfoForPaymentResponse) GetProductVariantId() string {
	if x != nil {
		return x.ProductVariantId
	}
	return ""
}

func (x *ProdInfoForPaymentResponse) GetOriginalUnitPrice() float64 {
	if x != nil {
		return x.OriginalUnitPrice
	}
	return 0
}

func (x *ProdInfoForPaymentResponse) GetDiscountUnitPrice() float64 {
	if x != nil {
		return x.DiscountUnitPrice
	}
	return 0
}

func (x *ProdInfoForPaymentResponse) GetTaxClass() string {
	if x != nil {
		return x.TaxClass
	}
	return ""
}

var File_partner_payment_proto protoreflect.FileDescriptor

var file_partner_payment_proto_rawDesc = string([]byte{
	0x0a, 0x15, 0x70, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x5f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x50, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x50, 0x72,
	0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x46, 0x6f, 0x72, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x49, 0x6e, 0x66,
	0x6f, 0x46, 0x6f, 0x72, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x65, 0x0a, 0x19, 0x50, 0x72, 0x6f,
	0x64, 0x49, 0x6e, 0x66, 0x6f, 0x46, 0x6f, 0x72, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x12, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x5f, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x10, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61,
	0x6e, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x22, 0x52, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x46,
	0x6f, 0x72, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x31, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x46, 0x6f, 0x72, 0x50, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x22, 0xc7, 0x01, 0x0a, 0x1a, 0x50, 0x72, 0x6f, 0x64, 0x49, 0x6e, 0x66,
	0x6f, 0x46, 0x6f, 0x72, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x76,
	0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x10, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x49,
	0x64, 0x12, 0x2e, 0x0a, 0x13, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x75, 0x6e,
	0x69, 0x74, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x11,
	0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x55, 0x6e, 0x69, 0x74, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x12, 0x2e, 0x0a, 0x13, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x75, 0x6e,
	0x69, 0x74, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x11,
	0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x55, 0x6e, 0x69, 0x74, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x61, 0x78, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x61, 0x78, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x42, 0x15,
	0x5a, 0x13, 0x2e, 0x2f, 0x70, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_partner_payment_proto_rawDescOnce sync.Once
	file_partner_payment_proto_rawDescData []byte
)

func file_partner_payment_proto_rawDescGZIP() []byte {
	file_partner_payment_proto_rawDescOnce.Do(func() {
		file_partner_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_partner_payment_proto_rawDesc), len(file_partner_payment_proto_rawDesc)))
	})
	return file_partner_payment_proto_rawDescData
}

var file_partner_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_partner_payment_proto_goTypes = []any{
	(*GetProdInfoForPaymentRequest)(nil),  // 0: GetProdInfoForPaymentRequest
	(*ProdInfoForPaymentRequest)(nil),     // 1: ProdInfoForPaymentRequest
	(*GetProdInfoForPaymentResponse)(nil), // 2: GetProdInfoForPaymentResponse
	(*ProdInfoForPaymentResponse)(nil),    // 3: ProdInfoForPaymentResponse
}
var file_partner_payment_proto_depIdxs = []int32{
	1, // 0: GetProdInfoForPaymentRequest.items:type_name -> ProdInfoForPaymentRequest
	3, // 1: GetProdInfoForPaymentResponse.items:type_name -> ProdInfoForPaymentResponse
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_partner_payment_proto_init() }
func file_partner_payment_proto_init() {
	if File_partner_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_partner_payment_proto_rawDesc), len(file_partner_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_partner_payment_proto_goTypes,
		DependencyIndexes: file_partner_payment_proto_depIdxs,
		MessageInfos:      file_partner_payment_proto_msgTypes,
	}.Build()
	File_partner_payment_proto = out.File
	file_partner_payment_proto_goTypes = nil
	file_partner_payment_proto_depIdxs = nil
}
