// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: partner_supplier.proto

package partner_proto_gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterSupplierRequest struct {
	state             protoimpl.MessageState    `protogen:"open.v1"`
	CompanyName       string                    `protobuf:"bytes,1,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	ContactPhone      string                    `protobuf:"bytes,2,opt,name=contact_phone,json=contactPhone,proto3" json:"contact_phone,omitempty"`
	TaxId             string                    `protobuf:"bytes,3,opt,name=tax_id,json=taxId,proto3" json:"tax_id,omitempty"`
	BusinessAddressId int64                     `protobuf:"varint,4,opt,name=business_address_id,json=businessAddressId,proto3" json:"business_address_id,omitempty"`
	LogoCompanyUrl    string                    `protobuf:"bytes,5,opt,name=logo_company_url,json=logoCompanyUrl,proto3" json:"logo_company_url,omitempty"`
	Description       *string                   `protobuf:"bytes,6,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Documents         *RegisterSupplierDocument `protobuf:"bytes,7,opt,name=documents,proto3" json:"documents,omitempty"`
	UserId            int64                     `protobuf:"varint,8,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterSupplierRequest) Reset() {
	*x = RegisterSupplierRequest{}
	mi := &file_partner_supplier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSupplierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSupplierRequest) ProtoMessage() {}

func (x *RegisterSupplierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_partner_supplier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSupplierRequest.ProtoReflect.Descriptor instead.
func (*RegisterSupplierRequest) Descriptor() ([]byte, []int) {
	return file_partner_supplier_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterSupplierRequest) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *RegisterSupplierRequest) GetContactPhone() string {
	if x != nil {
		return x.ContactPhone
	}
	return ""
}

func (x *RegisterSupplierRequest) GetTaxId() string {
	if x != nil {
		return x.TaxId
	}
	return ""
}

func (x *RegisterSupplierRequest) GetBusinessAddressId() int64 {
	if x != nil {
		return x.BusinessAddressId
	}
	return 0
}

func (x *RegisterSupplierRequest) GetLogoCompanyUrl() string {
	if x != nil {
		return x.LogoCompanyUrl
	}
	return ""
}

func (x *RegisterSupplierRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *RegisterSupplierRequest) GetDocuments() *RegisterSupplierDocument {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *RegisterSupplierRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type RegisterSupplierDocument struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BusinessLicense string                 `protobuf:"bytes,1,opt,name=business_license,json=businessLicense,proto3" json:"business_license,omitempty"`
	TaxCertificate  string                 `protobuf:"bytes,2,opt,name=tax_certificate,json=taxCertificate,proto3" json:"tax_certificate,omitempty"`
	IdCardFront     string                 `protobuf:"bytes,3,opt,name=id_card_front,json=idCardFront,proto3" json:"id_card_front,omitempty"`
	IdCardBack      string                 `protobuf:"bytes,4,opt,name=id_card_back,json=idCardBack,proto3" json:"id_card_back,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterSupplierDocument) Reset() {
	*x = RegisterSupplierDocument{}
	mi := &file_partner_supplier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSupplierDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSupplierDocument) ProtoMessage() {}

func (x *RegisterSupplierDocument) ProtoReflect() protoreflect.Message {
	mi := &file_partner_supplier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSupplierDocument.ProtoReflect.Descriptor instead.
func (*RegisterSupplierDocument) Descriptor() ([]byte, []int) {
	return file_partner_supplier_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterSupplierDocument) GetBusinessLicense() string {
	if x != nil {
		return x.BusinessLicense
	}
	return ""
}

func (x *RegisterSupplierDocument) GetTaxCertificate() string {
	if x != nil {
		return x.TaxCertificate
	}
	return ""
}

func (x *RegisterSupplierDocument) GetIdCardFront() string {
	if x != nil {
		return x.IdCardFront
	}
	return ""
}

func (x *RegisterSupplierDocument) GetIdCardBack() string {
	if x != nil {
		return x.IdCardBack
	}
	return ""
}

type RegisterSupplierResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterSupplierResponse) Reset() {
	*x = RegisterSupplierResponse{}
	mi := &file_partner_supplier_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSupplierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSupplierResponse) ProtoMessage() {}

func (x *RegisterSupplierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_partner_supplier_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSupplierResponse.ProtoReflect.Descriptor instead.
func (*RegisterSupplierResponse) Descriptor() ([]byte, []int) {
	return file_partner_supplier_proto_rawDescGZIP(), []int{2}
}

var File_partner_supplier_proto protoreflect.FileDescriptor

var file_partner_supplier_proto_rawDesc = string([]byte{
	0x0a, 0x16, 0x70, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x5f, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x69,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xdb, 0x02, 0x0a, 0x17, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70,
	0x61, 0x6e, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x61,
	0x63, 0x74, 0x5f, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x15, 0x0a, 0x06,
	0x74, 0x61, 0x78, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x61,
	0x78, 0x49, 0x64, 0x12, 0x2e, 0x0a, 0x13, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x5f,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x11, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x6c, 0x6f, 0x67, 0x6f, 0x5f, 0x63, 0x6f, 0x6d, 0x70,
	0x61, 0x6e, 0x79, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x6c,
	0x6f, 0x67, 0x6f, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x55, 0x72, 0x6c, 0x12, 0x25, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x88, 0x01, 0x01, 0x12, 0x37, 0x0a, 0x09, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x52, 0x09, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xb4, 0x01, 0x0a, 0x18, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x44, 0x6f, 0x63, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x12, 0x29, 0x0a, 0x10, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x5f,
	0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x62,
	0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x4c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x12, 0x27,
	0x0a, 0x0f, 0x74, 0x61, 0x78, 0x5f, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x74, 0x61, 0x78, 0x43, 0x65, 0x72, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x22, 0x0a, 0x0d, 0x69, 0x64, 0x5f, 0x63, 0x61,
	0x72, 0x64, 0x5f, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x69, 0x64, 0x43, 0x61, 0x72, 0x64, 0x46, 0x72, 0x6f, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0c, 0x69,
	0x64, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x5f, 0x62, 0x61, 0x63, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x69, 0x64, 0x43, 0x61, 0x72, 0x64, 0x42, 0x61, 0x63, 0x6b, 0x22, 0x1a, 0x0a,
	0x18, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x15, 0x5a, 0x13, 0x2e, 0x2f, 0x70,
	0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_partner_supplier_proto_rawDescOnce sync.Once
	file_partner_supplier_proto_rawDescData []byte
)

func file_partner_supplier_proto_rawDescGZIP() []byte {
	file_partner_supplier_proto_rawDescOnce.Do(func() {
		file_partner_supplier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_partner_supplier_proto_rawDesc), len(file_partner_supplier_proto_rawDesc)))
	})
	return file_partner_supplier_proto_rawDescData
}

var file_partner_supplier_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_partner_supplier_proto_goTypes = []any{
	(*RegisterSupplierRequest)(nil),  // 0: RegisterSupplierRequest
	(*RegisterSupplierDocument)(nil), // 1: RegisterSupplierDocument
	(*RegisterSupplierResponse)(nil), // 2: RegisterSupplierResponse
}
var file_partner_supplier_proto_depIdxs = []int32{
	1, // 0: RegisterSupplierRequest.documents:type_name -> RegisterSupplierDocument
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_partner_supplier_proto_init() }
func file_partner_supplier_proto_init() {
	if File_partner_supplier_proto != nil {
		return
	}
	file_partner_supplier_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_partner_supplier_proto_rawDesc), len(file_partner_supplier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_partner_supplier_proto_goTypes,
		DependencyIndexes: file_partner_supplier_proto_depIdxs,
		MessageInfos:      file_partner_supplier_proto_msgTypes,
	}.Build()
	File_partner_supplier_proto = out.File
	file_partner_supplier_proto_goTypes = nil
	file_partner_supplier_proto_depIdxs = nil
}
