// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: partner_order.proto

package partner_proto_gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSupplierInfoForOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SupplierIds   []int64                `protobuf:"varint,1,rep,packed,name=supplier_ids,json=supplierIds,proto3" json:"supplier_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSupplierInfoForOrderRequest) Reset() {
	*x = GetSupplierInfoForOrderRequest{}
	mi := &file_partner_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSupplierInfoForOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSupplierInfoForOrderRequest) ProtoMessage() {}

func (x *GetSupplierInfoForOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_partner_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSupplierInfoForOrderRequest.ProtoReflect.Descriptor instead.
func (*GetSupplierInfoForOrderRequest) Descriptor() ([]byte, []int) {
	return file_partner_order_proto_rawDescGZIP(), []int{0}
}

func (x *GetSupplierInfoForOrderRequest) GetSupplierIds() []int64 {
	if x != nil {
		return x.SupplierIds
	}
	return nil
}

type GetSupplierInfoForOrderResponse struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Data          []*SupplierInfoForOrderResponse `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSupplierInfoForOrderResponse) Reset() {
	*x = GetSupplierInfoForOrderResponse{}
	mi := &file_partner_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSupplierInfoForOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSupplierInfoForOrderResponse) ProtoMessage() {}

func (x *GetSupplierInfoForOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_partner_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSupplierInfoForOrderResponse.ProtoReflect.Descriptor instead.
func (*GetSupplierInfoForOrderResponse) Descriptor() ([]byte, []int) {
	return file_partner_order_proto_rawDescGZIP(), []int{1}
}

func (x *GetSupplierInfoForOrderResponse) GetData() []*SupplierInfoForOrderResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type SupplierInfoForOrderResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SupplierId        int64                  `protobuf:"varint,1,opt,name=supplier_id,json=supplierId,proto3" json:"supplier_id,omitempty"`
	SupplierName      string                 `protobuf:"bytes,2,opt,name=supplier_name,json=supplierName,proto3" json:"supplier_name,omitempty"`
	SupplierThumbnail string                 `protobuf:"bytes,3,opt,name=supplier_thumbnail,json=supplierThumbnail,proto3" json:"supplier_thumbnail,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SupplierInfoForOrderResponse) Reset() {
	*x = SupplierInfoForOrderResponse{}
	mi := &file_partner_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupplierInfoForOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupplierInfoForOrderResponse) ProtoMessage() {}

func (x *SupplierInfoForOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_partner_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupplierInfoForOrderResponse.ProtoReflect.Descriptor instead.
func (*SupplierInfoForOrderResponse) Descriptor() ([]byte, []int) {
	return file_partner_order_proto_rawDescGZIP(), []int{2}
}

func (x *SupplierInfoForOrderResponse) GetSupplierId() int64 {
	if x != nil {
		return x.SupplierId
	}
	return 0
}

func (x *SupplierInfoForOrderResponse) GetSupplierName() string {
	if x != nil {
		return x.SupplierName
	}
	return ""
}

func (x *SupplierInfoForOrderResponse) GetSupplierThumbnail() string {
	if x != nil {
		return x.SupplierThumbnail
	}
	return ""
}

var File_partner_order_proto protoreflect.FileDescriptor

var file_partner_order_proto_rawDesc = string([]byte{
	0x0a, 0x13, 0x70, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x5f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x43, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x53, 0x75, 0x70, 0x70,
	0x6c, 0x69, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x46, 0x6f, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x75, 0x70, 0x70, 0x6c,
	0x69, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0b, 0x73,
	0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x49, 0x64, 0x73, 0x22, 0x54, 0x0a, 0x1f, 0x47, 0x65,
	0x74, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x46, 0x6f, 0x72,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x53, 0x75,
	0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x46, 0x6f, 0x72, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x93, 0x01, 0x0a, 0x1c, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x46, 0x6f, 0x72, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x75, 0x70, 0x70, 0x6c,
	0x69, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2d, 0x0a, 0x12, 0x73, 0x75, 0x70, 0x70, 0x6c,
	0x69, 0x65, 0x72, 0x5f, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x11, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x72, 0x54, 0x68, 0x75,
	0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x42, 0x15, 0x5a, 0x13, 0x2e, 0x2f, 0x70, 0x61, 0x72, 0x74,
	0x6e, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_partner_order_proto_rawDescOnce sync.Once
	file_partner_order_proto_rawDescData []byte
)

func file_partner_order_proto_rawDescGZIP() []byte {
	file_partner_order_proto_rawDescOnce.Do(func() {
		file_partner_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_partner_order_proto_rawDesc), len(file_partner_order_proto_rawDesc)))
	})
	return file_partner_order_proto_rawDescData
}

var file_partner_order_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_partner_order_proto_goTypes = []any{
	(*GetSupplierInfoForOrderRequest)(nil),  // 0: GetSupplierInfoForOrderRequest
	(*GetSupplierInfoForOrderResponse)(nil), // 1: GetSupplierInfoForOrderResponse
	(*SupplierInfoForOrderResponse)(nil),    // 2: SupplierInfoForOrderResponse
}
var file_partner_order_proto_depIdxs = []int32{
	2, // 0: GetSupplierInfoForOrderResponse.data:type_name -> SupplierInfoForOrderResponse
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_partner_order_proto_init() }
func file_partner_order_proto_init() {
	if File_partner_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_partner_order_proto_rawDesc), len(file_partner_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_partner_order_proto_goTypes,
		DependencyIndexes: file_partner_order_proto_depIdxs,
		MessageInfos:      file_partner_order_proto_msgTypes,
	}.Build()
	File_partner_order_proto = out.File
	file_partner_order_proto_goTypes = nil
	file_partner_order_proto_depIdxs = nil
}
