// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: product_variant.proto

package partner_proto_gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckAvailableProductVariantRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProductVariantId string                 `protobuf:"bytes,1,opt,name=product_variant_id,json=productVariantId,proto3" json:"product_variant_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CheckAvailableProductVariantRequest) Reset() {
	*x = CheckAvailableProductVariantRequest{}
	mi := &file_product_variant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAvailableProductVariantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAvailableProductVariantRequest) ProtoMessage() {}

func (x *CheckAvailableProductVariantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_variant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAvailableProductVariantRequest.ProtoReflect.Descriptor instead.
func (*CheckAvailableProductVariantRequest) Descriptor() ([]byte, []int) {
	return file_product_variant_proto_rawDescGZIP(), []int{0}
}

func (x *CheckAvailableProductVariantRequest) GetProductVariantId() string {
	if x != nil {
		return x.ProductVariantId
	}
	return ""
}

type CheckAvailableProductVariantResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IsAvailable       bool                   `protobuf:"varint,1,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	InventoryQuantity int64                  `protobuf:"varint,2,opt,name=inventory_quantity,json=inventoryQuantity,proto3" json:"inventory_quantity,omitempty"`
	ProductVariantId  string                 `protobuf:"bytes,3,opt,name=product_variant_id,json=productVariantId,proto3" json:"product_variant_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CheckAvailableProductVariantResponse) Reset() {
	*x = CheckAvailableProductVariantResponse{}
	mi := &file_product_variant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAvailableProductVariantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAvailableProductVariantResponse) ProtoMessage() {}

func (x *CheckAvailableProductVariantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_variant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAvailableProductVariantResponse.ProtoReflect.Descriptor instead.
func (*CheckAvailableProductVariantResponse) Descriptor() ([]byte, []int) {
	return file_product_variant_proto_rawDescGZIP(), []int{1}
}

func (x *CheckAvailableProductVariantResponse) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

func (x *CheckAvailableProductVariantResponse) GetInventoryQuantity() int64 {
	if x != nil {
		return x.InventoryQuantity
	}
	return 0
}

func (x *CheckAvailableProductVariantResponse) GetProductVariantId() string {
	if x != nil {
		return x.ProductVariantId
	}
	return ""
}

var File_product_variant_proto protoreflect.FileDescriptor

var file_product_variant_proto_rawDesc = string([]byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x53, 0x0a, 0x23, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c,
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x22, 0xa6, 0x01, 0x0a,
	0x24, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x61, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x41,
	0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x2d, 0x0a, 0x12, 0x69, 0x6e, 0x76, 0x65,
	0x6e, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x51,
	0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x2c, 0x0a, 0x12, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x5f, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x10, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x56, 0x61, 0x72, 0x69,
	0x61, 0x6e, 0x74, 0x49, 0x64, 0x42, 0x15, 0x5a, 0x13, 0x2e, 0x2f, 0x70, 0x61, 0x72, 0x74, 0x6e,
	0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_product_variant_proto_rawDescOnce sync.Once
	file_product_variant_proto_rawDescData []byte
)

func file_product_variant_proto_rawDescGZIP() []byte {
	file_product_variant_proto_rawDescOnce.Do(func() {
		file_product_variant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_variant_proto_rawDesc), len(file_product_variant_proto_rawDesc)))
	})
	return file_product_variant_proto_rawDescData
}

var file_product_variant_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_product_variant_proto_goTypes = []any{
	(*CheckAvailableProductVariantRequest)(nil),  // 0: CheckAvailableProductVariantRequest
	(*CheckAvailableProductVariantResponse)(nil), // 1: CheckAvailableProductVariantResponse
}
var file_product_variant_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_product_variant_proto_init() }
func file_product_variant_proto_init() {
	if File_product_variant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_variant_proto_rawDesc), len(file_product_variant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_product_variant_proto_goTypes,
		DependencyIndexes: file_product_variant_proto_depIdxs,
		MessageInfos:      file_product_variant_proto_msgTypes,
	}.Build()
	File_product_variant_proto = out.File
	file_product_variant_proto_goTypes = nil
	file_product_variant_proto_depIdxs = nil
}
