// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: product_variant.proto

package partner_proto_gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckAvailableProductVariantRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProductVariantId string                 `protobuf:"bytes,1,opt,name=product_variant_id,json=productVariantId,proto3" json:"product_variant_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CheckAvailableProductVariantRequest) Reset() {
	*x = CheckAvailableProductVariantRequest{}
	mi := &file_product_variant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAvailableProductVariantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAvailableProductVariantRequest) ProtoMessage() {}

func (x *CheckAvailableProductVariantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_variant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAvailableProductVariantRequest.ProtoReflect.Descriptor instead.
func (*CheckAvailableProductVariantRequest) Descriptor() ([]byte, []int) {
	return file_product_variant_proto_rawDescGZIP(), []int{0}
}

func (x *CheckAvailableProductVariantRequest) GetProductVariantId() string {
	if x != nil {
		return x.ProductVariantId
	}
	return ""
}

type CheckAvailableProductVariantResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IsAvailable       bool                   `protobuf:"varint,1,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	InventoryQuantity int64                  `protobuf:"varint,2,opt,name=inventory_quantity,json=inventoryQuantity,proto3" json:"inventory_quantity,omitempty"`
	ProductVariantId  string                 `protobuf:"bytes,3,opt,name=product_variant_id,json=productVariantId,proto3" json:"product_variant_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CheckAvailableProductVariantResponse) Reset() {
	*x = CheckAvailableProductVariantResponse{}
	mi := &file_product_variant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAvailableProductVariantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAvailableProductVariantResponse) ProtoMessage() {}

func (x *CheckAvailableProductVariantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_variant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAvailableProductVariantResponse.ProtoReflect.Descriptor instead.
func (*CheckAvailableProductVariantResponse) Descriptor() ([]byte, []int) {
	return file_product_variant_proto_rawDescGZIP(), []int{1}
}

func (x *CheckAvailableProductVariantResponse) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

func (x *CheckAvailableProductVariantResponse) GetInventoryQuantity() int64 {
	if x != nil {
		return x.InventoryQuantity
	}
	return 0
}

func (x *CheckAvailableProductVariantResponse) GetProductVariantId() string {
	if x != nil {
		return x.ProductVariantId
	}
	return ""
}

type GetProductInfoCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       []*ProductInfoCart     `protobuf:"bytes,1,rep,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductInfoCartRequest) Reset() {
	*x = GetProductInfoCartRequest{}
	mi := &file_product_variant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductInfoCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductInfoCartRequest) ProtoMessage() {}

func (x *GetProductInfoCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_variant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductInfoCartRequest.ProtoReflect.Descriptor instead.
func (*GetProductInfoCartRequest) Descriptor() ([]byte, []int) {
	return file_product_variant_proto_rawDescGZIP(), []int{2}
}

func (x *GetProductInfoCartRequest) GetRequest() []*ProductInfoCart {
	if x != nil {
		return x.Request
	}
	return nil
}

type ProductInfoCart struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProductId        string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductVariantId string                 `protobuf:"bytes,2,opt,name=product_variant_id,json=productVariantId,proto3" json:"product_variant_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProductInfoCart) Reset() {
	*x = ProductInfoCart{}
	mi := &file_product_variant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductInfoCart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductInfoCart) ProtoMessage() {}

func (x *ProductInfoCart) ProtoReflect() protoreflect.Message {
	mi := &file_product_variant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductInfoCart.ProtoReflect.Descriptor instead.
func (*ProductInfoCart) Descriptor() ([]byte, []int) {
	return file_product_variant_proto_rawDescGZIP(), []int{3}
}

func (x *ProductInfoCart) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductInfoCart) GetProductVariantId() string {
	if x != nil {
		return x.ProductVariantId
	}
	return ""
}

type GetProductInfoCartResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	ProductInfo   []*ProductInfoCartResponse `protobuf:"bytes,1,rep,name=product_info,json=productInfo,proto3" json:"product_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductInfoCartResponse) Reset() {
	*x = GetProductInfoCartResponse{}
	mi := &file_product_variant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductInfoCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductInfoCartResponse) ProtoMessage() {}

func (x *GetProductInfoCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_variant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductInfoCartResponse.ProtoReflect.Descriptor instead.
func (*GetProductInfoCartResponse) Descriptor() ([]byte, []int) {
	return file_product_variant_proto_rawDescGZIP(), []int{4}
}

func (x *GetProductInfoCartResponse) GetProductInfo() []*ProductInfoCartResponse {
	if x != nil {
		return x.ProductInfo
	}
	return nil
}

type ProductInfoCartResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ProductId               string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductVariantId        string                 `protobuf:"bytes,2,opt,name=product_variant_id,json=productVariantId,proto3" json:"product_variant_id,omitempty"`
	ProductName             string                 `protobuf:"bytes,3,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Price                   float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	DiscountPrice           float64                `protobuf:"fixed64,6,opt,name=discount_price,json=discountPrice,proto3" json:"discount_price,omitempty"`
	ProductVariantThumbnail string                 `protobuf:"bytes,7,opt,name=product_variant_thumbnail,json=productVariantThumbnail,proto3" json:"product_variant_thumbnail,omitempty"`
	ProductVariantAlt       string                 `protobuf:"bytes,8,opt,name=product_variant_alt,json=productVariantAlt,proto3" json:"product_variant_alt,omitempty"`
	Currency                string                 `protobuf:"bytes,9,opt,name=currency,proto3" json:"currency,omitempty"`
	VariantName             string                 `protobuf:"bytes,10,opt,name=variant_name,json=variantName,proto3" json:"variant_name,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ProductInfoCartResponse) Reset() {
	*x = ProductInfoCartResponse{}
	mi := &file_product_variant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductInfoCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductInfoCartResponse) ProtoMessage() {}

func (x *ProductInfoCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_variant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductInfoCartResponse.ProtoReflect.Descriptor instead.
func (*ProductInfoCartResponse) Descriptor() ([]byte, []int) {
	return file_product_variant_proto_rawDescGZIP(), []int{5}
}

func (x *ProductInfoCartResponse) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductInfoCartResponse) GetProductVariantId() string {
	if x != nil {
		return x.ProductVariantId
	}
	return ""
}

func (x *ProductInfoCartResponse) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *ProductInfoCartResponse) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductInfoCartResponse) GetDiscountPrice() float64 {
	if x != nil {
		return x.DiscountPrice
	}
	return 0
}

func (x *ProductInfoCartResponse) GetProductVariantThumbnail() string {
	if x != nil {
		return x.ProductVariantThumbnail
	}
	return ""
}

func (x *ProductInfoCartResponse) GetProductVariantAlt() string {
	if x != nil {
		return x.ProductVariantAlt
	}
	return ""
}

func (x *ProductInfoCartResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ProductInfoCartResponse) GetVariantName() string {
	if x != nil {
		return x.VariantName
	}
	return ""
}

type UpdateQuantityProductVariantWhenConfirmedRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Quantity         int64                  `protobuf:"varint,1,opt,name=quantity,proto3" json:"quantity,omitempty"`
	ProductVariantId string                 `protobuf:"bytes,2,opt,name=product_variant_id,json=productVariantId,proto3" json:"product_variant_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateQuantityProductVariantWhenConfirmedRequest) Reset() {
	*x = UpdateQuantityProductVariantWhenConfirmedRequest{}
	mi := &file_product_variant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuantityProductVariantWhenConfirmedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuantityProductVariantWhenConfirmedRequest) ProtoMessage() {}

func (x *UpdateQuantityProductVariantWhenConfirmedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_variant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuantityProductVariantWhenConfirmedRequest.ProtoReflect.Descriptor instead.
func (*UpdateQuantityProductVariantWhenConfirmedRequest) Descriptor() ([]byte, []int) {
	return file_product_variant_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateQuantityProductVariantWhenConfirmedRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *UpdateQuantityProductVariantWhenConfirmedRequest) GetProductVariantId() string {
	if x != nil {
		return x.ProductVariantId
	}
	return ""
}

type UpdateQuantityProductVariantWhenConfirmedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQuantityProductVariantWhenConfirmedResponse) Reset() {
	*x = UpdateQuantityProductVariantWhenConfirmedResponse{}
	mi := &file_product_variant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQuantityProductVariantWhenConfirmedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQuantityProductVariantWhenConfirmedResponse) ProtoMessage() {}

func (x *UpdateQuantityProductVariantWhenConfirmedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_variant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQuantityProductVariantWhenConfirmedResponse.ProtoReflect.Descriptor instead.
func (*UpdateQuantityProductVariantWhenConfirmedResponse) Descriptor() ([]byte, []int) {
	return file_product_variant_proto_rawDescGZIP(), []int{7}
}

var File_product_variant_proto protoreflect.FileDescriptor

var file_product_variant_proto_rawDesc = string([]byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x53, 0x0a, 0x23, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c,
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x22, 0xa6, 0x01, 0x0a,
	0x24, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x73, 0x5f, 0x61, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x69, 0x73, 0x41,
	0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x2d, 0x0a, 0x12, 0x69, 0x6e, 0x76, 0x65,
	0x6e, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x51,
	0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x2c, 0x0a, 0x12, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x5f, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x10, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x56, 0x61, 0x72, 0x69,
	0x61, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x47, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2a, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x43, 0x61, 0x72, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x5e,
	0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x61, 0x72,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64,
	0x12, 0x2c, 0x0a, 0x12, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x76, 0x61, 0x72, 0x69,
	0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x59,
	0x0a, 0x1a, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x0c,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0b, 0x70, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0xf1, 0x02, 0x0a, 0x17, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x12, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f,
	0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x10, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74,
	0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x64,
	0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x0d, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x12, 0x3a, 0x0a, 0x19, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x76, 0x61,
	0x72, 0x69, 0x61, 0x6e, 0x74, 0x5f, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x17, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x56, 0x61,
	0x72, 0x69, 0x61, 0x6e, 0x74, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x12, 0x2e,
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e,
	0x74, 0x5f, 0x61, 0x6c, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x70, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x41, 0x6c, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x76, 0x61,
	0x72, 0x69, 0x61, 0x6e, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x7c, 0x0a,
	0x30, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x57, 0x68, 0x65,
	0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x2c, 0x0a,
	0x12, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x33, 0x0a, 0x31, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x51, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x56, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x57, 0x68, 0x65, 0x6e, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x15, 0x5a, 0x13, 0x2e, 0x2f, 0x70, 0x61, 0x72, 0x74, 0x6e, 0x65, 0x72, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x5f, 0x67, 0x65, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_product_variant_proto_rawDescOnce sync.Once
	file_product_variant_proto_rawDescData []byte
)

func file_product_variant_proto_rawDescGZIP() []byte {
	file_product_variant_proto_rawDescOnce.Do(func() {
		file_product_variant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_variant_proto_rawDesc), len(file_product_variant_proto_rawDesc)))
	})
	return file_product_variant_proto_rawDescData
}

var file_product_variant_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_product_variant_proto_goTypes = []any{
	(*CheckAvailableProductVariantRequest)(nil),               // 0: CheckAvailableProductVariantRequest
	(*CheckAvailableProductVariantResponse)(nil),              // 1: CheckAvailableProductVariantResponse
	(*GetProductInfoCartRequest)(nil),                         // 2: GetProductInfoCartRequest
	(*ProductInfoCart)(nil),                                   // 3: ProductInfoCart
	(*GetProductInfoCartResponse)(nil),                        // 4: GetProductInfoCartResponse
	(*ProductInfoCartResponse)(nil),                           // 5: ProductInfoCartResponse
	(*UpdateQuantityProductVariantWhenConfirmedRequest)(nil),  // 6: UpdateQuantityProductVariantWhenConfirmedRequest
	(*UpdateQuantityProductVariantWhenConfirmedResponse)(nil), // 7: UpdateQuantityProductVariantWhenConfirmedResponse
}
var file_product_variant_proto_depIdxs = []int32{
	3, // 0: GetProductInfoCartRequest.request:type_name -> ProductInfoCart
	5, // 1: GetProductInfoCartResponse.product_info:type_name -> ProductInfoCartResponse
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_product_variant_proto_init() }
func file_product_variant_proto_init() {
	if File_product_variant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_variant_proto_rawDesc), len(file_product_variant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_product_variant_proto_goTypes,
		DependencyIndexes: file_product_variant_proto_depIdxs,
		MessageInfos:      file_product_variant_proto_msgTypes,
	}.Build()
	File_product_variant_proto = out.File
	file_product_variant_proto_goTypes = nil
	file_product_variant_proto_depIdxs = nil
}
